# Generated by Django 3.2.6 on 2022-02-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(default='385fjfjrjvjdsiijrujfjut', max_length=100),
        ),
    ]
